version: "3"
services:

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    restart: always
    image: redis:7-alpine
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ${REDIS_DATA_DIR}:/data

  mastodon-web:
    image: tootsuite/mastodon:v4.2
    restart: always
    env_file: 
      - mastodon.env
      - mastodon-secrets.env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    depends_on:
      - db
      - redis
    volumes:
      - ${MASTODON_DIR}/system:/mastodon/public/system
      - ${MASTODON_DIR}/packs:/mastodon/public/packs
      - ${MASTODON_DIR}/assets:/mastodon/public/assets
    environment:
      - DB_NAME=${POSTGRES_USER}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      
  mastodon-streaming:
    image: tootsuite/mastodon:v4.2
    restart: always
    env_file: 
      - mastodon.env
      - mastodon-secrets.env
    command: node ./streaming
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=${POSTGRES_USER}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}

  mastodon-sidekiq:
    image: tootsuite/mastodon:v4.2
    restart: always
    env_file: 
      - mastodon.env
      - mastodon-secrets.env
    command: bundle exec sidekiq
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    depends_on:
      - db
      - redis
    volumes:
      - ${MASTODON_DIR}/system:/mastodon/public/system
    environment:
      - DB_NAME=${POSTGRES_USER}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}

