version: "3"
services:
  channels-dvr:
    image: fancybits/channels-dvr:latest
    container_name: channels-dvr
    restart: on-failure:10
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CHANNELS_DATA_DIR}/config:/channels-dvr
      - ${CHANNELS_DATA_DIR}/recordings:/shares/DVR
    networks:
      prinet:
        ipv4_address: 192.168.5.2

networks:
  prinet:
    name: macvlan-net
    external: true
