version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    volumes:
      - ${HOMEBRIDGE_DATA_DIR}/volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    networks:
      prinet:
        ipv4_address: 192.168.5.3

networks:
  prinet:
    name: macvlan-net
    external: true

